# Run verbosely
verbose = false

# The location to compute the visibilities for
[location]
latitude-deg = 52.0
longitude-deg = 4.0
altitude-m = 0.0

# Settings related to the NTRIP Client and Caster
[ntrip]
software-version = 0.3                  # Version of this software to identify with
software-name = "gnss-monitor"          # Name of this software to identify with
address = "ntrip.kadaster.nl"           # URL of the caster
port = 2101                             # Port of the caster
mountpoint = "BCEP00KAD0"               # Mount point to use
use-ssl = false                         # Use SSL for the connection
ntrip-v2 = false                        # Make a NTRIP V2 Connection
include-host-header = false             # Include host header, should be on for IBSS
username-password = "anonymous:pass"    # The username and password to connect with

# Settings related to the LED strip
[leds]

# General settings related to the LED strip
[leds.general]
led-count = 100             # Number of LED pixels.
gpio-pin = 18               # GPIO pin connected to the pixels (18 uses PWM, 10 uses SPI /dev/spidev0.0).
led-freq-hz = 800e3         # LED signal frequency in hertz (usually 800khz)
dma-channel = 10            # DMA channel to use for generating signal (try 10)
led-max-brightness = 255    # Set to 0 for darkest and 255 for brightest
invert-signal = false       # True to invert the signal (when using NPN transistor level shift)
channel = 0                 # set to '1' for GPIOs 13, 19, 41, 45 or 53
led-strip-type = "_rpi_ws281x.WS2811_STRIP_RGB" # The type of LED strip, see https://github.com/HarmvZ/rpi_ws281x_mock/blob/master/rpi_ws281x/rpi_ws281x_mock.py#L128
update-interval = 1         # Update interval of the LEDs in seconds

# Settings for the LEDs related to the satellites
[leds.satellites]
color-healthy = [0, 255, 0]                                 # [R,G,B] color to use for healthy satellites
color-unhealthy = [255, 0, 0]                               # [R,G,B] color to use for unhealthy satellites
color-plane = [255, 255, 255]                               # [R,G,B] color to use to display the orbital plane
brightness-early-late-plane = 0.5                           # Brightness for the early and late LEDs in the orbital plane animation
min-elev = 0.0                                              # Minimum elevation
min-elev-brightness = 127                                   # Brightness corresponding to the minimum elevation
max-elev = 90.0                                             # Maximum elevation
max-elev-brightness = 255                                   # Brightness corresponding to the maximum elevation
orbit-plane-a = [43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89]
orbit-plane-b = [109, 110, 111, 112, 113, 114, 115, 116, 117, 118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129, 130, 131, 132, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142, 143, 144, 145, 146, 147, 148, 149, 150, 151, 152, 153, 154, 155, 156]
orbit-plane-c = [157, 158, 159, 160, 161, 162, 163, 164, 165, 166, 167, 168, 169, 170, 171, 172, 173, 174, 175, 176, 177, 178, 179, 180, 181, 182, 183, 184, 185, 186, 187, 188, 189, 190, 191, 192, 193, 194, 195, 196, 197, 198, 199]
map-prns = [31, 1, 21, 27, 30, 02, 25, 24, 31, 13, 15, 34, 36, 22, 11, 10, 12, 33, 26, 05, 09, 06, 04, 19, 29, 07, 08, 03]
map-leds = [179, 174, 165, 159, 198, 193, 189, 185, 82, 88, 44, 48, 52, 58, 63, 68, 72, 78, 146, 139, 134, 127, 122, 112, 155, 151]
#orbit-plane-a = [71, 72, 73, 74, 75, 76, 77, 78, 79, 80]    # LED numbers corresponding to orbital plane A
#orbit-plane-b = [81, 82, 83, 84, 85, 86, 87, 88, 89, 90]    # LED numbers corresponding to orbital plane B
#orbit-plane-c = [91, 92, 93, 94, 95, 96, 97, 98, 99, 100]   # LED numbers corresponding to orbital plane C
#map-prns = [1, 2 ,3 ,4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 29, 30, 31, 33, 34, 36]
#map-leds = [0, 1, 2, 3, 4, 5, 6, 7, 8,  9, 10, 11, 12, 13, 14, 15, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 28, 29, 30, 32, 33, 35]