verbose = false         # Run verbosely
simulation-speed = 1    # Simulation speed (1 = realtime)

# The location to compute the visibilities for
[location]
latitude-deg = 52.0
longitude-deg = 4.0
altitude-m = 0.0

# Settings related to the NTRIP Client and Caster
[ntrip]
software-version = 0.3                  # Version of this software to identify with
software-name = "gnss-monitor"          # Name of this software to identify with
address = "ntrip.kadaster.nl"           # URL of the caster
port = 2101                             # Port of the caster
mountpoint = "BCEP00KAD0"               # Mount point to use
use-ssl = false                         # Use SSL for the connection
ntrip-v2 = false                        # Make a NTRIP V2 Connection
include-host-header = false             # Include host header, should be on for IBSS
username-password = "anonymous:pass"    # The username and password to connect with

# Settings related to the LED strip
[leds]

# General settings related to the LED strip
[leds.general]
led-count = 200             # Number of LED pixels.
gpio-pin = 18               # GPIO pin connected to the pixels (18 uses PWM, 10 uses SPI /dev/spidev0.0).
led-freq-hz = 800000        # LED signal frequency in hertz (usually 800khz)
dma-channel = 10            # DMA channel to use for generating signal (try 10)
led-max-brightness = 255    # Set to 0 for darkest and 255 for brightest
invert-signal = false       # True to invert the signal (when using NPN transistor level shift)
channel = 0                 # set to '1' for GPIOs 13, 19, 41, 45 or 53
led-strip-type = 'WS2811_STRIP_RGB' # The type of LED strip, see gnss_monitor/ledcontroller.py
update-interval = 1.0       # Update interval of the LEDs in seconds
plane-interval = 4.0        # Interval for the plane LEDs

# Settings for the LEDs related to the satellites
[leds.satellites]
color-healthy = [0, 255, 0]                                 # [R,G,B] color to use for healthy satellites
color-unhealthy = [255, 0, 0]                               # [R,G,B] color to use for unhealthy satellites
color-unknown = [255, 165, 0]                               # [R,G,B] color to use for unhealthy satellites
color-plane = [255, 255, 255]                               # [R,G,B] color to use to display the orbital plane
brightness-early-late-plane = 0.5                           # Brightness for the early and late LEDs in the orbital plane animation
min-elev = 0.0                                              # Minimum elevation
min-elev-brightness = 0                                   # Brightness corresponding to the minimum elevation
max-elev = 90.0                                             # Maximum elevation
max-elev-brightness = 255                                   # Brightness corresponding to the maximum elevation
orbit-plane-a = [199, 198, 197, 196, 195, 194, 193, 192, 191, 190, 189, 188, 187, 186, 185, 184, 183, 182, 181, 180, 179, 178, 177, 176, 175, 174, 173, 172, 171, 170, 169, 168, 167, 166, 165, 164, 163, 162, 161, 160, 159, 158, 157]
orbit-plane-b = [156, 155, 154, 153, 152, 151, 150, 149, 148, 147, 146, 145, 144, 143, 142, 141, 140, 139, 138, 137, 136, 135, 134, 133, 132, 131, 130, 129, 128, 127, 126, 125, 124, 123, 122, 121, 120, 119, 118, 117, 116, 115, 114, 113, 112, 111, 110, 109]
orbit-plane-c = [43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89]
map-prns = [31, 1, 21, 27, 30, 2, 25, 24, 13, 15, 34, 36, 22, 11, 10, 12, 33, 26, 5, 9, 6, 4, 19, 29, 7, 8, 3]
map-leds = [179, 174, 165, 159, 198, 193, 189, 185, 82, 88, 44, 48, 52, 58, 63, 68, 72, 78, 146, 139, 134, 127, 122, 117, 112, 155, 151]

